# Generated by Django 4.2.7 on 2023-11-20 23:20

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_employee_company_created_at_company_date_from_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(max_length=30)),
                ('date_from', models.DateField(default=datetime.date(1900, 1, 1))),
                ('date_to', models.DateField(default=datetime.date(9999, 12, 31))),
                ('tax_id', models.CharField(max_length=10)),
                ('email', models.EmailField(default='', max_length=254)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('deleted', models.DateField(default=datetime.date(9999, 12, 31))),
                ('user', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='company',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='updated_at',
            new_name='updated',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='created_at',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='updated_at',
            new_name='updated',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='email',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='tax_id',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
        migrations.AddField(
            model_name='company',
            name='deleted',
            field=models.DateField(default=datetime.date(9999, 12, 31)),
        ),
        migrations.AddField(
            model_name='employee',
            name='company',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='payroll.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='deleted',
            field=models.DateField(default=datetime.date(9999, 12, 31)),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_from',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='person',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='payroll.person'),
        ),
    ]
