# Generated by Django 4.2.7 on 2023-11-21 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0005_company_tax_id_alter_company_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_demo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='company',
            name='tax_id',
            field=models.CharField(default='', max_length=10, null=True),
        ),
    ]
