# Generated by Django 4.2.7 on 2023-11-24 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0010_auto_20231123_2236'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Laws',
            new_name='Law',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='laws',
            new_name='law',
        ),
    ]
