# Generated by Django 4.2.7 on 2023-12-02 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0017_employee_department_employee_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='date_from',
        ),
        migrations.RemoveField(
            model_name='person',
            name='date_to',
        ),
        migrations.AddField(
            model_name='person',
            name='birth_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
