# Generated by Django 4.2.7 on 2023-12-02 03:19

from django.db import migrations

def populate_employment_status(apps, schema_editor):
    templates = [
        {'id': 1, 'name': 'Full Time (30+ hours per week)'},
        {'id': 2, 'name': 'Part-Time (20–29 hours per week)'},
        {'id': 3, 'name': 'Part-Time (0–19 hours per week)'},
        {'id': 4, 'name': 'Variable (hours vary every week)'},
        {'id': 5, 'name': 'Seasonal employee'},
        {'id': 6, 'name': 'Owners'},
    ]
    EmploymentStatus = apps.get_model("payroll", "employmentStatus")
    for t in templates:
        accounting = EmploymentStatus()
        accounting.id = t['id']
        accounting.name = t['name']
        accounting.save()

class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0019_employeetype_employmentstatus_wageper_employee_wage_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_employment_status),
    ]
