# Generated by Django 4.2.7 on 2023-12-02 03:34

from django.db import migrations

def populate_employee_type(apps, schema_editor):
    templates = [
        {'id': 1, 'name': 'Salary/No Overtime'},
        {'id': 2, 'name': 'Salary/Eligible for Overtime'},
        {'id': 3, 'name': 'Paid by the Hour'},
        {'id': 4, 'name': 'Commission only/No overtime'},
        {'id': 5, 'name': 'Commission only/Eligible for overtime'},
    ]
    EmployeeType = apps.get_model("payroll", "employeeType")
    for t in templates:
        accounting = EmployeeType()
        accounting.id = t['id']
        accounting.name = t['name']
        accounting.save()

class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0020_auto_20231202_0319'),
    ]

    operations = [
        migrations.RunPython(populate_employee_type),
    ]
