# Generated by Django 4.2.7 on 2023-12-04 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0022_auto_20231202_0338'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('class_name', models.CharField(max_length=150)),
                ('group', models.CharField(max_length=150)),
                ('method', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='PayrollDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_period', models.DateField()),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('days', models.IntegerField(blank=True, default=0, null=True)),
                ('hours', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=4, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.employee')),
                ('payment_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payroll.paymenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_period', models.DateField()),
                ('days', models.IntegerField(blank=True, default=0, null=True)),
                ('hours', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=4, null=True)),
                ('wage', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('bonus', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('taxes', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('deductions', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('payments', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.employee')),
            ],
        ),
    ]
