# Generated by Django 4.2.7 on 2023-12-04 11:50

from django.db import migrations

def populate_PaymentType(apps, schema_editor):
    templates = [
        {'id': 1, 'name': 'Wage', 'class_name': 'Earnings', 'group': 'Earnings', 'method': 'Wage'},
        {'id': 2, 'name': 'Bonus', 'class_name': 'Earnings', 'group': 'Earnings', 'method': 'Bonus'},
        {'id': 3, 'name': 'Contribution', 'class_name': 'Deductions', 'group': 'Deductions', 'method': 'Contribution'},
        {'id': 4, 'name': 'Personal Income Tax', 'class_name': 'Deductions', 'group': 'Taxes', 'method': 'Personal Income Tax'},
        {'id': 5, 'name': 'Military Collection', 'class_name': 'Deductions', 'group': 'Taxes', 'method': 'Military Collection'},
        {'id': 6, 'name': 'Advance payment', 'class_name': 'Deductions', 'group': 'Payment', 'method': 'Advance payment'},
        {'id': 7, 'name': 'Payment', 'class_name': 'Deductions', 'group': 'Payment', 'method': 'Payment'},
    ]
    PaymentType = apps.get_model("payroll", "PaymentType")
    for t in templates:
        accounting = PaymentType()
        accounting.id = t['id']
        accounting.name = t['name']
        accounting.class_name = t['class_name']
        accounting.group = t['group']
        accounting.method = t['method']
        accounting.save()

class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0023_paymenttype_payrolldetails_payroll'),
    ]

    operations = [
        migrations.RunPython(populate_PaymentType),
    ]
